project_id = "qdctfnxxexibteoeqyfi"

[functions.extract-document]
verify_jwt = false

[functions.extract-property]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.generate-proposal]
verify_jwt = false

[functions.generate-docx]
verify_jwt = false

[functions.public-submission]
verify_jwt = false

[functions.public-proposta]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
